course = "Python Programming"
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.rstrip())
print(course.lstrip())
print(course.find("Pro"))
print(course.replace("P", "J"))
print("Pro" in course)
print("Swift" not in course)